[Tests] add missing include
fix:

/src/pinocchio/unittest/liegroups.cpp:455:23: error: no template named 'vector' in namespace 'boost::mpl'
  typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
          ~~~~~~~~~~~~^
/src/pinocchio/unittest/liegroups.cpp:479:23: error: no template named 'vector' in namespace 'boost::mpl'
  typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
          ~~~~~~~~~~~~^
/src/pinocchio/unittest/liegroups.cpp:506:23: error: no template named 'vector' in namespace 'boost::mpl'
  typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
          ~~~~~~~~~~~~^
/src/pinocchio/unittest/liegroups.cpp:530:23: error: no template named 'vector' in namespace 'boost::mpl'
  typedef boost::mpl::vector<  VectorSpaceOperationTpl<1,Scalar,Options>
          ~~~~~~~~~~~~^